name: For initial build of docker image

on: workflow_dispatch


jobs:
  Image-build-push:
    uses: https://github.com/org-547/reusable/blob/main/.github/workflows/img-build-push.yml@main
    with:
      initial: yes
      app-component: app-server-2
      container: back-cnt
      port: 5000
