name: Backend workflow

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    uses: org-547/reusable/.github/workflows/img-build-push.yml@main
    with:
      app-component: app-server-2
      container: back-cnt
      port: 5000
    secrets:  
      docker-uname: ${{ secrets.DOCKER_UNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN}}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    env:
      IMAGE_TAG: ${{ needs.Image-build-push.outputs.image-tag }}

    steps:
      - name: Check out other repo from same organization
        uses: actions/checkout@v3
        with:
          repository: org-547/for-compose
          #token: ${{ secrets.GIT_TOKEN }}
          ref: main

      - name: Install docker compose
        run: |
          echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$USER
          sudo apt install docker-compose -y

      - name: Docker-compose down and up
        run: |
          export FRONT_TAG=latest
          export BACK_TAG=${{ env.IMAGE_TAG }}
          echo "Frontend tag is: $FRONT_TAG"
          echo "Backend tag is: $BACK_TAG"
          docker-compose down 
          docker-compose up -d
    
    
