name: Backend workflow

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.tagging.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and tag of docker image
        id: tagging
        run: |
          docker build -t ${{ secrets.DOCKER_UNAME }}/app-server-2:${GITHUB_SHA::7} .
          echo "IMAGE_TAG=${{ GITHUB_SHA::7 }}" >> $GITHUB_OUTPUT

      - name: Test newly created build image
        run: docker run --rm -d --name back-cnt -p 5000:5000 ${{ secrets.DOCKER_UNAME }}/app-server-2:${GITHUB_SHA::7}

      - name: Push image to DockerHub
        if  : success()
        run : |
          docker login -u ${{ secrets.DOCKER_UNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_UNAME }}/app-server-2:${GITHUB_SHA::7}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    env:
      IMAGE_TAG: ${{ needs.Image-build-push.outputs.image-tag }}

    steps:
      - name: Check out other repo from same organization
        uses: actions/checkout@master
        with:
          repository: first-org/for-compose
          token: ${{ secrets.GIT_TOKEN }}

      - name: Docker-compose down and up
        run: |
          export BACK_TAG=${{ env.IMAGE_TAG }}
          docker-compose down
          docker-compose up
    
    
