name: Backend workflow..

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    uses: org-547/reusable/.github/workflows/img-build-push.yml@main
    with:
      app-component: app-server-2
      container: back-cnt
      port: 5000
    secrets:  
      docker-uname: ${{ secrets.DOCKER_UNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN}}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    steps:
      - name: Check out other repo from same organization
        uses: actions/checkout@v3
        with:
          repository: org-547/for-compose
          ref: main

      #- name: Install docker compose
        #run: |
          #echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$USER
          #printf 'student\n' | sudo apt install docker-compose -y
          #echo "student" | sudo -S apt update
          #docker-compose --version
          #echo "Hello from me"

      - name: mesage
        run: echo "some message"

      - name: Extract BACK_TAG value
        run: |
          echo "another message"
          BACK_TAG_FROM_YML=$(grep -oP '(?<=image: some-user/app-server-2:)\${BACK_TAG}' docker-compose.yml)
          echo "BACK_TAG=$BACK_TAG_FROM_YML" 

      #- name: Docker-compose down and up
        #run: |
          #export FRONT_TAG=first
          #export BACK_TAG=${GITHUB_SHA::7}
          #echo "Frontend tag is: $FRONT_TAG"
          #echo "Backend tag is: $BACK_TAG"
          #docker-compose down 
          #docker-compose up -d
    
    
