name: Backend workflow..

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    uses: org-547/reusable/.github/workflows/img-build-push.yml@main
    with:
      app-component: app-server-2
      container: back-cnt
      port: 5000
    secrets:  
      docker-uname: ${{ secrets.DOCKER_UNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN}}

  Change-image-tag-and-deploy:
    needs: [Image-build-push]
    runs-on: self-hosted

    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Check out other repo from same organization
        uses: actions/checkout@v3
        with:
          repository: org-547/for-compose
          ref: main

      #- name: Install docker compose
        #run: |
          #echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$USER
          #printf 'student\n' | sudo apt install docker-compose -y
          #echo "student" | sudo -S apt update
          #docker-compose --version
          #echo "Hello from me"

      - name: mesage
        run: echo "some message"

      - name: Extract current frontend image-tag
        id: get-tag
        run: |
          echo "another message"
          CURRENT_FRONT_TAG=$(grep -oP '(?<=image: terezabisharyan/app-client-2:)\${FRONT_TAG}' docker-compose.yml)
          echo "tag=$CURRENT_FRONT_TAG" >> $GITHUB_OUTPUT
          echo "Current frontend image-tag is: $CURRENT_FRONT_TAG" 

      - name: Check backend container existence
        run: |
          if !docker ps -a --format '{{.Names}}' | grep -q 'back-cnt'; then
            docker run --rm -d --name back-cnt --network host ${{ secrets.DOCKER_UNAME }}/app-server:${{ needs.Image-build-push.outputs.image-tag }}
          else
            echo "Container with name 'back-cnt' already exists!"
            docker stop back-cnt || true
            docker rm back-cnt || true
            docker run --rm -d --name back-cnt --network host ${{ secrets.DOCKER_UNAME }}/app-server:${{ needs.Image-build-push.outputs.image-tag }}
          fi 

      - name: Docker-compose down and up
        run: |
          if [ ${{ steps.get-tag.outputs.tag }}  == '$FRONT_TAG' ]; then
            export FRONT_TAG=first
          fi  
          export BACK_TAG=${{ needs.Image-build-push.outputs.image-tag }}
          echo "Backend tag is: $BACK_TAG"
          docker-compose down 
          docker-compose up -d
    
    
